
package org.pathvisio.core;

// Do not modify, this file is automatically generated
public class Revision
{
	public static final String REVISION = "3468M";
	public static final String VERSION = "2.0.11";
}
	  