#!/bin/sh
APPDIR=`dirname $0`;
java  -Xmx256M -cp "$APPDIR/src:$APPDIR/bin:$APPDIR/lib/gwt-user.jar:$APPDIR/lib/gwt-dev-linux.jar" com.google.gwt.dev.GWTCompiler -out "$APPDIR/www" "$@" org.pathvisio.wikipathways.AtlasMapper;
