#!/bin/sh
MYCLASSPATH=\
build/v1:\
lib/BrowserLauncher.jar:\
lib/batik/batik-awt-util.jar:\
lib/batik/batik-bridge.jar:\
lib/batik/batik-css.jar:\
lib/batik/batik-dom.jar:\
lib/batik/batik-ext.jar:\
lib/batik/batik-extension.jar:\
lib/batik/batik-gvt.jar:\
lib/batik/batik-parser.jar:\
lib/batik/batik-script.jar:\
lib/batik/batik-svg-dom.jar:\
lib/batik/batik-svggen.jar:\
lib/batik/batik-transcoder.jar:\
lib/batik/batik-util.jar:\
lib/batik/batik-xml.jar:\
lib/batik/pdf-transcoder.jar:\
lib/batik/xml-apis.jar:\
lib/derby.jar:\
lib/jdom.jar:\
lib/org.eclipse.core.commands.jar:\
lib/org.eclipse.equinox.common.jar:\
lib/org.eclipse.equinox.supplement.jar:\
lib/org.eclipse.jface.jar:\
lib/resources.jar:\
lib/swt-linux-lib/swt.jar:\
lib/swt-linux-lib.jar

java -ea -cp $MYCLASSPATH org.pathvisio.gpmldiff.GpmlDiff $1 $2 $3 $4 $5 $6 $7 $8 $9