//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.16 at 12:23:52 PM PDT 
//


package dtd.kegg;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the dtd.kegg package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: dtd.kegg
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Graphics }
     * 
     */
    public Graphics createGraphics() {
        return new Graphics();
    }

    /**
     * Create an instance of {@link Entry }
     * 
     */
    public Entry createEntry() {
        return new Entry();
    }

    /**
     * Create an instance of {@link Pathway }
     * 
     */
    public Pathway createPathway() {
        return new Pathway();
    }

    /**
     * Create an instance of {@link Subtype }
     * 
     */
    public Subtype createSubtype() {
        return new Subtype();
    }

    /**
     * Create an instance of {@link Component }
     * 
     */
    public Component createComponent() {
        return new Component();
    }

    /**
     * Create an instance of {@link Relation }
     * 
     */
    public Relation createRelation() {
        return new Relation();
    }

    /**
     * Create an instance of {@link Substrate }
     * 
     */
    public Substrate createSubstrate() {
        return new Substrate();
    }

    /**
     * Create an instance of {@link Product }
     * 
     */
    public Product createProduct() {
        return new Product();
    }

    /**
     * Create an instance of {@link Reaction }
     * 
     */
    public Reaction createReaction() {
        return new Reaction();
    }

    /**
     * Create an instance of {@link Alt }
     * 
     */
    public Alt createAlt() {
        return new Alt();
    }

}
