// PathVisio,
// a tool for data visualization and analysis using Biological Pathways
// Copyright 2006-2009 BiGCaT Bioinformatics
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
package org.pathvisio.core.biopax;

import java.util.EventObject;

/**
 * A BioPAX event is generated by BiopaxReferenceManager, when the status
 * of the BioPAX references changes, i.e. when a reference to a
 * BioPAX element is added / removed.
 *
 * This event is not used for changes to the contents of the
 * BioPAX element itself.
 */
public class BiopaxEvent extends EventObject
{
	/**
	 * Constructor for creating a new event.
	 * @param source The BiopaxReferenceManager that generated this event.
	 */
	public BiopaxEvent(BiopaxReferenceManager source) {
		super(source);
	}
}
